// should be autogenerated
const MsgFromElm = {
  LogToConsole: "LogToConsole",
  ReadFile: "ReadFile",
  StoreUserInLocal: "StoreUserInLocal",
  GetUserFromLocal: "GetUserFromLocal",
};

const MsgToElm = {
  ReceiveString: "ReceiveString",
  ReceiveBool: "ReceiveBool",
  ReceiveUser: "ReceiveUser",
};

module.exports = { MsgFromElm, MsgToElm };
