// should be autogenerated
const MsgFromElm = {
  Log: 'Log',
  Store: 'Store',
  Get: 'Get',
};

const MsgToElm = {
  ReceiveString: 'ReceiveString',
  ReceiveBool: 'ReceiveBool',
  ReceiveUser: 'ReceiveUser',
};

module.exports = { MsgFromElm, MsgToElm };
