// should be autogenerated
const MsgTypeFromElm = {
  Log: "Log",
  Store: "Store",
  Get: "Get",
};

const MsgTypeToElm = {
  ReceiveString: "ReceiveString",
  ReceiveBool: "ReceiveBool",
  ReceiveUser: "ReceiveUser",
};

module.exports = { MsgTypeFromElm };
